# Base image
FROM node:20-alpine

# Set work directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy project
COPY . .

# Expose port
EXPOSE 5000

# Run server
CMD ["npm", "start"]
