version: "3.8"

volumes:
  smartschool-db-data:

networks:
  smartschool-network:
    name: smartschool-network

services:
  config-service:
    build: ./smartSchool-config/config-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=config-service
      - SERVER_PORT=8080
      # - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/sandjonyves/smartSchool-config.git
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=file:///cloud-config/
    volumes:
      - ./smartSchool-config/cloud-config:/cloud-config
    networks:
      - smartschool-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  registry-service:
    build: ./smartSchool-config/registry-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - SPRING_APPLICATION_NAME=registry-service
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false
    networks:
      - smartschool-network
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  proxy-service:
    build: ./smartSchool-config/proxy-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - SPRING_APPLICATION_NAME=proxy-service
      - SERVER_PORT=8081

      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_GLOBALCORS_CORS-CONFIGURATIONS___PATHPATTERN__ALLOWED-ORIGINS=http://localhost:8082,http://frontend-service:8082
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_GLOBALCORS_CORS-CONFIGURATIONS___PATHPATTERN__ALLOWED-HEADERS=*
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_GLOBALCORS_CORS-CONFIGURATIONS___PATHPATTERN__ALLOWED-METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_GLOBALCORS_CORS-CONFIGURATIONS___PATHPATTERN__ALLOW-CREDENTIALS=true

    networks:
      - smartschool-network
    depends_on:
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy
  
  rabbitmq-service:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smartschool-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  inscription-service:
    build: ./SmartSchool-backend/inscription-service
    ports:
      - "5000:5000"

    networks:
      - smartschool-network
    depends_on:
      registry-service:
        condition: service_healthy
      rabbitmq-service:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5


  registration-service:
    build: ./SmartSchool-backend/registration-service
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq-service:5672
    networks:
      - smartschool-network

    depends_on:
      registry-service:
        condition: service_healthy
      rabbitmq-service:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-notes:
    build: ./SmartSchool-backend/service-notes
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_HOST=rabbitmq-service
    networks:
      - smartschool-network
    depends_on:
      registry-service:
        condition: service_healthy
      rabbitmq-service:
        condition: service_healthy

  authentification-service:
    build: ./SmartSchool-backend/systeme_authentification
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_HOST=rabbitmq-service
    networks:
      - smartschool-network
    depends_on:
      rabbitmq-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy


  frontend-service:
    build: ./SmartSchool-front
    ports:
      - "8082:8082"
    volumes:
      - ./SmartSchool-front:/app           # monte ton code local
      - /app/node_modules  
    networks:
      - smartschool-network
    
   