# Generated by Django 5.2.7 on 2025-11-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id_enseignant',
        ),
    ]
