apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service-deployment
  namespace: smartschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service-container
        image: 010912112706.dkr.ecr.eu-west-1.amazonaws.com/smartschool/proxy-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"

        # --- Eureka config ---
        - name: SPRING_APPLICATION_NAME
          value: "proxy-service"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://registry-service:8761/eureka/"

        # --- Gateway Discovery Locator ---
        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
          value: "true"
        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
          value: "true"

        # --- Config Server (si tu l'utilises) ---
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8080"
