# Generated by Django 5.2.7 on 2025-11-28 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_id', models.IntegerField()),
                ('classe_id', models.IntegerField(blank=True, null=True)),
                ('trimestre', models.IntegerField(blank=True, null=True)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('moyenne_classe', models.FloatField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=150)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=100)),
                ('sequences', models.JSONField(blank=True, default=dict)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bulletins.bulletin')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletin',
            },
        ),
    ]
