# Generated by Django 5.2.7 on 2025-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignebulletin',
            options={'verbose_name': 'Ligne de bulletin', 'verbose_name_plural': 'Lignes de bulletin'},
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='appreciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='matiere',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='sequences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
