# Utilise une image de base avec Java
FROM eclipse-temurin:17-jdk-jammy

# Définit le répertoire de travail
WORKDIR /app

# Copie le fichier JAR dans l'image
COPY target/registry-service.jar registry-service.jar

# Expose le port sur lequel l'application s'exécutera
EXPOSE 8761

# Définit la commande pour lancer l'application au démarrage du conteneur
ENTRYPOINT ["java", "-jar", "registry-service.jar"]
