# Nom du service
spring.application.name=proxy-service

# URL du Config Server
spring.cloud.config.uri=http://localhost:8080
spring.config.import=configserver:

# Port du gateway (optionnel, par défaut 8081)
server.port=8081

# CORS global pour tous les endpoints (nouvelle syntaxe)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:8082,http://172.20.10.4:8082

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true

# Logging pour debug
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
