# -------------------------------------------------------
# Nom du service
# -------------------------------------------------------
spring.application.name=proxy-service

# -------------------------------------------------------
# Configuration du Config Server
# -------------------------------------------------------
# URL du serveur de configuration
spring.cloud.config.uri=http://localhost:8080

# Importer la configuration distante
spring.config.import=configserver:

# -------------------------------------------------------
# Port du Gateway
# -------------------------------------------------------
server.port=8081

# -------------------------------------------------------
# Configuration CORS globale (WebFlux)
# -------------------------------------------------------
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:8082,http://192.168.0.104:8082
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# -------------------------------------------------------
# Logging
# -------------------------------------------------------
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.cors.reactive=DEBUG
