apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: smartschool-config-service:latest
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "native"
          - name: SERVER_PORT
            value: "8080"
          - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
            value: "file:/cloud-config/"