# Utilise Node pour construire et exécuter
FROM node:20-slim

# Crée le répertoire de travail
WORKDIR /app

# Copie les fichiers package et installe les dépendances
COPY package*.json ./
RUN npm install

# Copie le reste des fichiers
COPY . .
# Expose le port de ton app React
EXPOSE 8082

# Lance l'application
CMD ["npm", "run", "dev"]
