apiVersion: v1
kind: Service
metadata:
  name: inscription-service
  namespace: smartschool
spec:
  selector:
    app: inscription-service
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
