spring.application.name=config-service
server.port=8888

# Configuration du Config Server (Git distant contenant les fichiers de configuration)
spring.cloud.config.server.git.uri=https://github.com/sandjonyves/smartSchool-config.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

# Enregistrement du service dans Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Instance configuration
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Pour éviter les warnings SSL
spring.cloud.config.server.git.skipSslValidation=true